### ISSUE TITLE
Sending decrypted data to webhook instead of a web server.

### ISSUE THREAD

**Issue by xHector1337** [ScribblerCoder/BrowserThief#3]
I do not know any powershell but this addition would  make it better. I do not think connecting to our web server is not that stealth in the terms of red teaming.

**Comment by ScribblerCoder** [comment]
The powershell script already recieves the URL from arguments

https://github.com/ScribblerCoder/BrowserThief/blob/main/BrowserThief.ps1#L92

It can be set to any URL
